obj-y += afe.o audio_interct.o mi2s.o audio_dev_ctl.o voice.o snddev_data.o
obj-$(CONFIG_MARIMBA_CODEC) += snddev_icodec.o lpa.o
obj-y += audio_pcm.o audpp.o audio_mp3.o audio_wma.o
obj-y += audio_amrwb.o audio_wmapro.o audio_adpcm.o
obj-y += audio_aac.o audio_amrnb.o audio_evrc.o audio_qcelp.o
