# MSM Platform Support
snd-soc-msm-objs := msm-pcm.o msm7k-pcm.o
snd-soc-msm-dai-objs := msm-dai.o


obj-$(CONFIG_SND_MSM_SOC) += snd-soc-msm.o
obj-$(CONFIG_SND_MSM_DAI_SOC) += snd-soc-msm-dai.o

# MSM Machine Support
snd-soc-msm7k-objs := msm7201.o

obj-$(CONFIG_SND_MSM_SOC_MSM7K) += snd-soc-msm7k.o

snd-soc-qsd-objs := qsd8k.o  qsd8k-pcm.o

obj-$(CONFIG_SND_QSD_SOC) += snd-soc-qsd.o
