obj-$(CONFIG_QSD_AUDIO) += q6audio.o
obj-$(CONFIG_QSD_AUDIO) += pcm_out.o
obj-$(CONFIG_QSD_AUDIO) += pcm_in.o
obj-$(CONFIG_QSD_AUDIO) += mp3.o
obj-$(CONFIG_QSD_AUDIO) += audio_ctl.o
obj-$(CONFIG_QSD_AUDIO) += analog_audio.o
obj-$(CONFIG_QSD_AUDIO) += routing.o
